platform: &platform
    platform: android

device_config: &device_config
    ios:
        platformName: 'ios'
        platformVersion: '13.5'
        deviceName: 'iPhone 11 Pro MT'
        automationName: 'XCUITest'
        appPackage: ''
        appActivity: ''
        noReset: True
        folder: '/Users/username/Library/Developer/Xcode/DerivedData/WordPress-bgx/Build/Products/Debug-iphonesimulator/WordPress.app'
    android:
        platformName: 'android'
        platformVersion: '10'
        deviceName: 'emulator-5554'
        automationName: 'uiautomator2'
        appPackage: 'co.mona.android.staging'
        app: '/Users/billylam/Desktop/apk/1000454.apk'
        noReset: True
        fullReset: False

production:
    <<: *platform
    <<: *device_config